### ISSUE TITLE
Rerolling the same number without making it obvious

### ISSUE THREAD

**Issue by elliottm24** [ReynHisamoto/Cs301GroupYahtzee#7]
This might not necessarily be a bug, but it was something that made testing hard. When we were running the game initially it rerolled the same number several times. It wasn't obvious to me and the person I was with if it was working or not, so I would recommend that you install something to make it more obvious if a roll is successful. It will help for future testing as well as making it easy for players to tell what's going on. We discussed possibly making the screen flash to indicate this happening. I think either that or have text pop up on the screen telling you what you rolled.

**Comment by Apham24** [comment]
Implemented
